# file: action.yml
# version: 1.1.0
# guid: 4d9a2e7b-5c1f-4a3e-8b6d-9e2c7f4a1b8e

name: "Release Go Module"
description: "Release Go modules with GoReleaser, automatic SDK tagging and multi-module support"
author: "jdfalk"

branding:
  icon: "box"
  color: "blue"

inputs:
  module-path:
    description: "Path to Go module (relative to repository root)"
    required: false
    default: "."
  go-version:
    description: "Go version to use"
    required: false
    default: "1.23"
  tag:
    description: "Release tag (e.g., v1.2.3)"
    required: true
  is-sdk:
    description: "Whether this is an SDK module (enables SDK-specific tagging)"
    required: false
    default: "false"
  sdk-language:
    description: "SDK language (go, python, typescript, etc.)"
    required: false
    default: ""
  run-tests:
    description: "Whether to run tests before release"
    required: false
    default: "true"
  run-linters:
    description: "Whether to run linters before release"
    required: false
    default: "true"
  create-release:
    description: "Whether to create a GitHub release"
    required: false
    default: "true"
  release-notes:
    description: "Custom release notes (markdown)"
    required: false
    default: ""
  goreleaser-config:
    description: "Path to .goreleaser.yml config file"
    required: false
    default: ".goreleaser.yml"
  goreleaser-args:
    description: "Additional arguments to pass to GoReleaser"
    required: false
    default: ""
  skip-publish:
    description: "Skip publishing (use --snapshot)"
    required: false
    default: "false"
  github-token:
    description: "GitHub token for creating releases"
    required: false
    default: ${{ github.token }}

outputs:
  tag:
    description: "The tag that was created"
    value: ${{ steps.tag-output.outputs.tag }}
  sdk-tag:
    description: "The SDK-specific tag (if applicable)"
    value: ${{ steps.sdk-tag.outputs.sdk-tag }}
  release-url:
    description: "URL of the created release"
    value: ${{ steps.goreleaser.outputs.url }}
  artifacts:
    description: "List of artifacts created"
    value: ${{ steps.goreleaser.outputs.artifacts }}

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache-dependency-path: ${{ inputs.module-path }}/go.sum

    - name: Verify Go module
      working-directory: ${{ inputs.module-path }}
      run: |
        if [ ! -f "go.mod" ]; then
          echo "Error: go.mod not found in ${{ inputs.module-path }}"
          exit 1
        fi
        echo "Module: $(go list -m)"
      shell: bash

    - name: Run tests
      if: inputs.run-tests == 'true'
      working-directory: ${{ inputs.module-path }}
      run: |
        go test -v -race -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out
      shell: bash

    - name: Run linters
      if: inputs.run-linters == 'true'
      working-directory: ${{ inputs.module-path }}
      run: |
        go vet ./...
        if command -v golangci-lint &> /dev/null; then
          golangci-lint run
        fi
      shell: bash

    - name: Generate SDK tag
      id: sdk-tag
      if: inputs.is-sdk == 'true' && inputs.sdk-language != ''
      run: |
        SDK_TAG="${{ inputs.sdk-language }}/${{ inputs.tag }}"
        echo "sdk-tag=$SDK_TAG" >> $GITHUB_OUTPUT
        echo "Generated SDK tag: $SDK_TAG"
      shell: bash

    - name: Set tag output
      id: tag-output
      run: |
        MODULE_PATH="${{ inputs.module-path }}"
        if [ "$MODULE_PATH" != "." ]; then
          TAG="${MODULE_PATH}/${{ inputs.tag }}"
        else
          TAG="${{ inputs.tag }}"
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Generated tag: $TAG"
      shell: bash

    - name: Create and push tags
      if: inputs.create-release == 'true'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        TAG="${{ steps.tag-output.outputs.tag }}"

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Create main tag
        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "Tag $TAG already exists, skipping creation"
        else
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG" || echo "Warning: Failed to push tag (may already exist remotely)"
          echo "Created and pushed tag: $TAG"
        fi

        # Create SDK tag if applicable
        if [ "${{ inputs.is-sdk }}" == "true" ] && [ -n "${{ steps.sdk-tag.outputs.sdk-tag }}" ]; then
          SDK_TAG="${{ steps.sdk-tag.outputs.sdk-tag }}"
          if git rev-parse "$SDK_TAG" >/dev/null 2>&1; then
            echo "SDK tag $SDK_TAG already exists, skipping creation"
          else
            git tag -a "$SDK_TAG" -m "SDK Release $SDK_TAG"
            git push origin "$SDK_TAG" || echo "Warning: Failed to push SDK tag (may already exist remotely)"
            echo "Created and pushed SDK tag: $SDK_TAG"
          fi
        fi
      shell: bash

    - name: Run GoReleaser
      id: goreleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean ${{ inputs.skip-publish == 'true' && '--snapshot' || '' }} ${{ inputs.goreleaser-args }}
        workdir: ${{ inputs.module-path }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Output summary
      run: |
        echo "## Go Module Release Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Module Path:** ${{ inputs.module-path }}" >> $GITHUB_STEP_SUMMARY
        echo "**Tag:** ${{ steps.tag-output.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
        if [ "${{ inputs.is-sdk }}" == "true" ]; then
          echo "**SDK Tag:** ${{ steps.sdk-tag.outputs.sdk-tag }}" >> $GITHUB_STEP_SUMMARY
        fi
        echo "**Go Version:** ${{ inputs.go-version }}" >> $GITHUB_STEP_SUMMARY
        if [ "${{ inputs.skip-publish }}" != "true" ]; then
          echo "**Release URL:** ${{ steps.goreleaser.outputs.url }}" >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
